In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('/Users/anishgulhane/Downloads/datasets after 14 sept/AmazonFoodReviews.csv')

In [3]:
df.shape

(568454, 10)

In [4]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [5]:
df.tail()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
568449,568450,B001EO7N10,A28KG5XORO54AY,Lettie D. Carter,0,0,5,1299628800,Will not do without,Great for sesame chicken..this is a good if no...
568450,568451,B003S1WTCU,A3I8AFVPEE8KI5,R. Sawyer,0,0,2,1331251200,disappointed,I'm disappointed with the flavor. The chocolat...
568451,568452,B004I613EE,A121AA1GQV751Z,"pksd ""pk_007""",2,2,5,1329782400,Perfect for our maltipoo,"These stars are small, so you can give 10-15 o..."
568452,568453,B004I613EE,A3IBEVCTXKNOH,"Kathy A. Welch ""katwel""",1,1,5,1331596800,Favorite Training and reward treat,These are the BEST treats for training and rew...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,srfell17,0,0,5,1338422400,Great Honey,"I am very satisfied ,product is as advertised,..."

In [6]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [7]:
df = df.iloc[:, [6, 9]]

In [8]:
df.head(1)

   Score                                               Text
0      5  I have bought several of the Vitality canned d...

In [9]:
df = df.rename(columns = {'Score': 'Y','Text': 'X'})

In [10]:
df.head()

   Y                                                  X
0  5  I have bought several of the Vitality canned d...
1  1  Product arrived labeled as Jumbo Salted Peanut...
2  4  This is a confection that has been around a fe...
3  2  If you are looking for the secret ingredient i...
4  5  Great taffy at a great price.  There was a wid...

In [11]:
df.Y.value_counts()

Y
5    363122
4     80655
1     52268
3     42640
2     29769
Name: count, dtype: int64

In [12]:
import nltk #  natural language tool kit (library used in NLP)
from nltk.corpus import stopwords

In [13]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anishgulhane/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [15]:
len(stopwords.words('english'))

198

In [16]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
df['X'] = df['X'].str.lower()

In [18]:
l1 = stopwords.words(('english'))
def text_process(mess):
    """
    1. remove the punctuation 
    2. remove the stopwords
    3. return the list of clean textwords
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)

    return[ word for word in nopunc.split() if word not in l1 ]

In [19]:
#df['X'].apply(text_process)# samjhane ke liye

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
# assign a ID/token number to each word

In [21]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(df["X"])

In [22]:
len(bow_transformer.vocabulary_)

240626

In [23]:
print(len(bow_transformer.vocabulary_))

240626

In [24]:
tdm = bow_transformer.transform(df['X'])

In [25]:
tdm.shape

(568454, 240626)

In [26]:
type(tdm)

scipy.sparse._csr.csr_matrix

In [27]:
df.head()

   Y                                                  X
0  5  i have bought several of the vitality canned d...
1  1  product arrived labeled as jumbo salted peanut...
2  4  this is a confection that has been around a fe...
3  2  if you are looking for the secret ingredient i...
4  5  great taffy at a great price.  there was a wid...

In [28]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(tdm, df.Y)

from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import *

train_y = train_y.astype(int)
test_y = test_y.astype(int)

In [29]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(train_x, train_y)#model build

LogisticRegression()

In [30]:
pred = logreg.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y, pred))

[[ 8805  1019   532   310  2323]
 [ 1755  2302  1019   426  1955]
 [  921   900  3598  1472  3695]
 [  456   404  1244  6284 11818]
 [  962   437   856  3220 85401]]
              precision    recall  f1-score   support

           1       0.68      0.68      0.68     12989
           2       0.45      0.31      0.37      7457
           3       0.50      0.34      0.40     10586
           4       0.54      0.31      0.39     20206
           5       0.81      0.94      0.87     90876

    accuracy                           0.75    142114
   macro avg       0.60      0.52      0.54    142114
weighted avg       0.72      0.75      0.72    142114

In [31]:
from sklearn.tree import DecisionTreeClassifier

# Limit max_depth and max_features to heavily speed up training
dt = DecisionTreeClassifier(max_depth=50, max_features='sqrt')
dt.fit(train_x, train_y)

pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

print(accuracy_score(test_y, pred), " ", 
      recall_score(test_y, pred, average='weighted'), " ", 
      precision_score(test_y, pred, average='weighted'))

[[ 1625    66   127   103 11068]
 [  203   537   114   106  6497]
 [  193    59   863   177  9294]
 [  202    81   195  1371 18357]
 [  546   148   366   508 89308]]
0.6593579802130684   0.6593579802130684   0.6344582995762589

In [32]:

from sklearn.ensemble import RandomForestClassifier

# Added n_estimators, max_depth, max_features, and n_jobs=-1
rf = RandomForestClassifier(n_estimators=50, max_depth=50, max_features='sqrt', n_jobs=-1, oob_score=True)
rf.fit(train_x, train_y)

pred = rf.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

# Remember to use average='weighted' here too!
print(accuracy_score(test_y, pred))

[[  725     0     0     0 12264]
 [    0   314     1     0  7142]
 [    0     0   476     2 10108]
 [    2     0     0   908 19296]
 [    1     0     1     1 90873]]
0.6564870456112698

In [33]:
# now in every model we build tillnow acuracy LogisticRegression,desision tree , random forest  is lower 
# so to fix it we will murge collums which will reduce error and make our previous 5x5 matrix to 3x3 matrix 
# here we are murging collum  1,2 = negative ,3 = neutral , 4,5 = positive

In [34]:
df.Y = df.Y.replace({1:1,2:1,3:2,4:3,5:3})

In [35]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(tdm, df.Y  )

from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import *

train_y = train_y.astype(int)
test_y = test_y.astype(int)

In [36]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(train_x, train_y)#model build

LogisticRegression()

In [37]:
pred = logreg.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y, pred))

[[ 14419   1104   4986]
 [  1929   3357   5142]
 [  2379   1628 107170]]
              precision    recall  f1-score   support

           1       0.77      0.70      0.73     20509
           2       0.55      0.32      0.41     10428
           3       0.91      0.96      0.94    111177

    accuracy                           0.88    142114
   macro avg       0.74      0.66      0.69    142114
weighted avg       0.87      0.88      0.87    142114

In [38]:
from sklearn.tree import DecisionTreeClassifier

# Limit max_depth and max_features to heavily speed up training
dt = DecisionTreeClassifier(max_depth=50, max_features='sqrt')
dt.fit(train_x, train_y)

pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

print(accuracy_score(test_y, pred), " ", 
      recall_score(test_y, pred, average='weighted'), " ", 
      precision_score(test_y, pred, average='weighted'))

[[  2607    148  17754]
 [   366    762   9300]
 [  1134    349 109694]]
0.7955796051057602   0.7955796051057602   0.7635552227023092

In [39]:

from sklearn.ensemble import RandomForestClassifier

# Added n_estimators, max_depth, max_features, and n_jobs=-1
rf = RandomForestClassifier(n_estimators=50, max_depth=50, max_features='sqrt', n_jobs=-1, oob_score=True)
rf.fit(train_x, train_y)

pred = rf.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

# Remember to use average='weighted' here too!
print(accuracy_score(test_y, pred))

[[   942      0  19567]
 [     0    318  10110]
 [     0      0 111177]]
0.7911746907412359

In [40]:
# we can also merge like collumb 1,2 = negative and collumn 3,4,5 = positive

In [41]:
df.Y = df.Y.replace({1:1,2:1,3:2,4:2,5:2})

In [42]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(tdm, df.Y, stratify=df.Y, test_size=0.25)
from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import *

train_y = train_y.astype(int)
test_y = test_y.astype(int)

In [43]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(train_x, train_y)#model build
pred = logreg.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y, pred))

[[ 21877   9292]
 [  4848 106097]]
              precision    recall  f1-score   support

           1       0.82      0.70      0.76     31169
           2       0.92      0.96      0.94    110945

    accuracy                           0.90    142114
   macro avg       0.87      0.83      0.85    142114
weighted avg       0.90      0.90      0.90    142114

In [44]:
from sklearn.tree import DecisionTreeClassifier

# Limit max_depth and max_features to heavily speed up training
dt = DecisionTreeClassifier(max_depth=50, max_features='sqrt')
dt.fit(train_x, train_y)

pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

print(accuracy_score(test_y, pred), " ", 
      recall_score(test_y, pred, average='weighted'), " ", 
      precision_score(test_y, pred, average='weighted'))

[[  5555  25614]
 [  2621 108324]]
0.8013214743093573   0.8013214743093573   0.7803960758863484

In [45]:

from sklearn.ensemble import RandomForestClassifier

# Added n_estimators, max_depth, max_features, and n_jobs=-1
rf = RandomForestClassifier(n_estimators=50, max_depth=50, max_features='sqrt', n_jobs=-1, oob_score=True)
rf.fit(train_x, train_y)

pred = rf.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)

# Remember to use average='weighted' here too!
print(accuracy_score(test_y, pred))

[[  1676  29493]
 [     5 110940]]
0.7924342429317308